### ISSUE TITLE
that queue's Dequeue and Peek methods can occur panic is unacceptable

### ISSUE THREAD

**Issue by Kristorkar** [zyedidia/generic#18]
make it return double values maybe better

also can make stack's Peek and Pop methods return double values

**Comment by shawc71** [comment]
It would seem reasonable that instead of panicing we change the method signatures to return a second argument indicating whether an element exists like:

```
func (q *Queue[T]) Dequeue() (T, bool)
func (q *Queue[T]) Peek() (T, bool)
```
however any such change will be backward incompatible, perhaps it is something that can go in a v2 if/when that ever comes but not sure if it is worth the headache to do a major version bump right now for this alone, what do you think @zyedidia ?

**Comment by jilleJr** [comment]
I've created a PR which suggests adding `TryDequeue` and `TryPeek`, which has the `(T, bool)` return type.

This keeps it backward compatible, while also providing the safe alternative methods.
